main: me.dolphin2410.webjelly.paper.WebJellyPlugin
version: 1.0.0
author: dolphin2410
name: webjelly
api-version: 1.19
libraries:
  - io.github.teamcheeze:jaw:1.0.4
  - org.eclipse.aether:aether-api:1.1.0
  - org.eclipse.aether:aether-spi:1.1.0
  - org.eclipse.aether:aether-impl:1.1.0
  - org.eclipse.aether:aether-connector-basic:1.1.0
  - org.eclipse.aether:aether-transport-file:1.1.0
  - org.eclipse.aether:aether-transport-http:1.1.0
  - org.apache.maven:maven-aether-provider:3.3.9
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0
